#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_ADMIN_USER" \
    --dbname "$DB_NAME" \
    -c "CREATE ROLE \"$POSTGRES_APP_USER\" LOGIN PASSWORD '$POSTGRES_APP_PASSWORD';" \
    -c "GRANT CONNECT ON DATABASE \"$DB_NAME\" TO \"$POSTGRES_APP_USER\";" \
    -c "GRANT USAGE ON SCHEMA public TO \"$POSTGRES_APP_USER\";" \
    -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO \"$POSTGRES_APP_USER\";" \
    -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO \"$POSTGRES_APP_USER\";" \
    -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON TYPES TO \"$POSTGRES_APP_USER\";"
